# Book settings
title: Strukturna biologija
author: Miha Pavšič
copyright: "2024"
logo: logo/logo_sbio_s.png
exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: false

# Information about where the book exists on the web
repository:
  url: https://github.com/mpavsic/sbio 
  path_to_book: sbio
  branch: main

# Customizations
html:
  favicon: favicon.ico
  use_issues_button: true
  use_edit_page_button: true
  use_repository_button: false
  home_page_in_navbar: true
  use_multitoc_numbering: false
  extra_navbar: ""
  baseurl: https://mpavsic.github.io/sbio
  extra_footer : |
      <div>
      <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://mpavsic.github.io/sbio">Strukturna biologija</a> by <span property="cc:attributionName">Miha Pavšič</span> is licensed under <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-ND 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1"></a></p>
      </div>

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false

parse:
  myst_url_schemes: [mailto, http, https]
#  myst_enable_extensions:
#    - deflist